# permissions for end users to view openstackipsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackipset-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackipsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackipsets/status
  verbs:
  - get
